-- local winshift = require("alexander.configs.plugins.winshift")
--
-- local M = {
-- 	{
-- 		"sindrets/winshift.nvim",
-- 		event = "BufEnter",
-- 		opts = winshift.opts,
-- 	},
-- }
--
-- return M
return {}
